#!/bin/sh
# este archivo hace que si algun test da fallido, el push no se ejecute
# Run the tests with Gradle
./gradle clean test

# Check if the tests passed
#-ne = not equal
# $? contiene el resultado de los tests, es una variable reservada
if [ $? -ne 0 ]; then
  echo "Tests failed, push aborted."
  exit 1
fi

# Allow the push to proceed
exit 0

