name: Java CI with Gradle

# Activar la pipeline cuando se realicen push en estas ramas
on:
  push:
    branches:
      - development # Rama de desarrollo
      - testing # Rama de pruebas
      - stage # Rama de producción

jobs:
  build:
    runs-on: ubuntu-latest # Ejecutar en un entorno de Ubuntu
    permissions:
      contents: read # Permiso para leer contenido del repositorio

    steps:
      - uses: actions/checkout@v4 # Clonar el repositorio
      - name: Configurar JDK 17
        uses: actions/setup-java@v4 # Configurar JDK
        with:
          java-version: "17" # Versión de Java a utilizar
          distribution: "temurin"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v3.1.0 # Configurar Gradle para el proyecto

      # Rama de desarrollo: Solo compilar, no ejecutar pruebas ni desplegar
      - name: Compilar para Desarrollo
        if: github.ref == 'refs/heads/development' # Solo se ejecuta si es la rama de desarrollo
        run: ./gradlew clean assemble # Limpiar y ensamblar el proyecto

      # Rama de pruebas: Ejecutar pruebas, no desplegar, detenerse después de las pruebas
      - name: Probar para Pruebas
        if: github.ref == 'refs/heads/testing' # Solo se ejecuta si es la rama de pruebas
        run: ./gradlew clean test # Limpiar y ejecutar pruebas

      # Rama de producción: Compilación completa, detenerse para aprobación manual antes de desplegar
      - name: Compilar para Producción
        if: github.ref == 'refs/heads/stage' # Solo se ejecuta si es la rama de producción
        run: ./gradlew clean build # Limpiar y construir el proyecto

  # Aprobación manual antes del despliegue
  manual-approval:
    needs: build # Este trabajo se ejecuta después de que el trabajo de compilación se complete
    runs-on: ubuntu-latest # Ejecutar en un entorno de Ubuntu
    if: github.ref == 'refs/heads/stage' # Solo se ejecuta si es la rama de producción

    steps:
      - name: Esperar aprobación manual
        run: |
          echo "Esperando aprobación manual antes del despliegue."
          echo "Puedes aprobar este flujo de trabajo desde la pestaña de Actions en GitHub."

  deploy:
    needs: manual-approval # El despliegue solo sucede después de la aprobación manual
    runs-on: ubuntu-latest # Ejecutar en un entorno de Ubuntu
    if: github.ref == 'refs/heads/stage' # Solo se ejecuta si es la rama de producción
    steps:
      - name: Desplegar en el entorno de producción
        run: |
          # Agrega aquí tus comandos de despliegue
          echo "Desplegando en el entorno de producción"
          scp -r ./build user@production-server:/path/to/deploy  # Copiar archivos al servidor de producción
          ssh user@production-server 'bash -s' << 'EOF'
            cd /path/to/deploy  # Cambiar al directorio de despliegue
            ./deploy-script.sh  # Ejecutar el script de despliegue
          EOF
